# Import necessary libraries

In [14]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor 
import xgboost as xgb 
from sklearn.ensemble import ExtraTreesRegressor 
from sklearn import metrics
import ast

# Load the datasets

In [10]:
dataframe = pd.read_csv( "../Database/preprocessed_data.csv") 
dataframe

,brand_0,brand_1,brand_2,brand_3,brand_4,price,dcity_0,dcity_1,dcity_2,dcity_3,...,Transit,dtime_category_0,dtime_category_1,dtime_category_2,atime_category_0,atime_category_1,atime_category_2,day_of_week,month,day_of_year
0,0,0,0,0,1,0.019123,0,0,0,0,...,0,0,0,1,0,0,1,2,12,340
1,0,0,0,1,0,0.020857,0,0,0,0,...,0,0,0,1,0,1,0,2,12,340
2,0,0,0,1,0,0.020857,0,0,0,0,...,0,0,0,1,0,1,0,2,12,340
3,0,0,0,1,0,0.020857,0,0,0,0,...,0,0,0,1,0,1,0,2,12,340
4,0,0,0,1,0,0.023730,0,0,0,0,...,0,0,1,0,0,1,0,2,12,340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49858,0,0,0,1,0,0.139011,1,0,0,0,...,0,1,0,0,0,1,1,0,12,359
49859,0,0,0,1,0,0.234971,1,0,0,0,...,0,1,0,0,0,1,1,0,12,359
49860,0,0,0,1,0,0.242303,1,0,0,0,...,0,1,0,0,0,1,1,0,12,359
49861,0,0,0,1,0,0.242674,1,0,0,0,...,0,1,0,0,0,1,1,0,12,359
49862,0,0,0,1,0,0.263828,1,0,0,0,...,0,1,0,0,0,1,1,0,12,359

In [53]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49863 entries, 0 to 49862
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   brand_0           49863 non-null  int64
 1   brand_1           49863 non-null  int64
 2   brand_2           49863 non-null  int64
 3   brand_3           49863 non-null  int64
 4   brand_4           49863 non-null  int64
 5   price             49863 non-null  float64
 6   dcity_0           49863 non-null  int64
 7   dcity_1           49863 non-null  int64
 8   dcity_2           49863 non-null  int64
 9   dcity_3           49863 non-null  int64
 10  dcity_4           49863 non-null  int64
 11  acity_0           49863 non-null  int64
 12  acity_1           49863 non-null  int64
 13  acity_2           49863 non-null  int64
 14  acity_3           49863 non-null  int64
 15  acity_4           49863 non-null  int64
 16  class_type        49863 non-null  int64
 17  flytime_hours     45177 non-null  float64
 18  Transit           49863 non-null  int64
 19  dtime_category_0  49863 non-null  int64
 20  dtime_category_1  49863 non-null  int64
 21  dtime_category_2  49863 non-null  int64
 22  atime_category_0  49863 non-null  int64
 23  atime_category_1  49863 non-null  int64
 24  atime_category_2  49863 non-null  int64
 25  day_of_week       49863 non-null  int64
 26  month             49863 non-null  int64
 27  day_of_year       49863 non-null  int64
dtypes: float64(2), int64(26)
memory usage: 10.7 MB

# Spliting the dataset

In [12]:
x=dataframe.drop(['price'],axis=1)
y=dataframe['price']

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((39890, 27), (9973, 27), (39890,), (9973,))

# Models

In [68]:
modelmlg = LinearRegression()
modeldcr = DecisionTreeRegressor() 
modelrfr = RandomForestRegressor() 
modelXGR = xgb.XGBRegressor() 
modelETR = ExtraTreesRegressor()
modelRE=Ridge()
modelLO=linear_model.Lasso(alpha=0.1)

MM = [modelmlg, modeldcr, modelrfr,  modelETR,  modelXGR, modelRE,modelLO] 

def MAPE (y_test, y_pred):
        y_test, y_pred = np.array(y_test), np.array(y_pred)
        return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

for models in MM: 
    
    models.fit(x_train, y_train) 

    y_pred = models.predict(x_test) 

    print('Model Name: ', models)

    print('Mean Absolute Error (MAE):', round(metrics.mean_absolute_error(y_test, y_pred),3))  
    print('Mean Squared Error (MSE):', round(metrics.mean_squared_error(y_test, y_pred),3))  
    print('Root Mean Squared Error (RMSE):', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))
    print('R2_score:', round(metrics.r2_score(y_test, y_pred),6))
    print('Root Mean Squared Log Error (RMSLE):', round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3))



    result = MAPE(y_test, y_pred)
    print('Mean Absolute Percentage Error (MAPE):', round(result, 2), '%')

    r_squared = round(metrics.r2_score(y_test, y_pred),6)
    adjusted_r_squared = round(1 - (1-r_squared)*(len(y)-1)/(len(y)-x.shape[1]-1),6)
    print('Adj R Square: ', adjusted_r_squared)
    print('------------------------------------------------------------------------------------------------------------') 
    
    new_row = {'Model Name' : models,
               'Mean_Absolute_Error_MAE' : metrics.mean_absolute_error(y_test, y_pred),
               'Adj_R_Square' : adjusted_r_squared,
               'Root_Mean_Squared_Error_RMSE' : np.sqrt(metrics.mean_squared_error(y_test, y_pred)),
               'Mean_Absolute_Percentage_Error_MAPE' : result,
               'Mean_Squared_Error_MSE' : metrics.mean_squared_error(y_test, y_pred),
               'Root_Mean_Squared_Log_Error_RMSLE': np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),
               'R2_score' : metrics.r2_score(y_test, y_pred)}
    Results.loc[len(Results)] = new_row

Model Name:  LinearRegression()
Mean Absolute Error (MAE): 0.077
Mean Squared Error (MSE): 0.013
Root Mean Squared Error (RMSE): 0.116
R2_score: 0.686102
Root Mean Squared Log Error (RMSLE): -2.154
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  0.685914
------------------------------------------------------------------------------------------------------------
Model Name:  DecisionTreeRegressor()
Mean Absolute Error (MAE): 0.062
Mean Squared Error (MSE): 0.01
Root Mean Squared Error (RMSE): 0.102
R2_score: 0.757426
Root Mean Squared Log Error (RMSLE): -2.283
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  0.757281
------------------------------------------------------------------------------------------------------------

C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

Model Name:  RandomForestRegressor()
Mean Absolute Error (MAE): 0.061
Mean Squared Error (MSE): 0.01
Root Mean Squared Error (RMSE): 0.099
R2_score: 0.771321
Root Mean Squared Log Error (RMSLE): -2.313
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  0.771184
------------------------------------------------------------------------------------------------------------

C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

Model Name:  ExtraTreesRegressor()
Mean Absolute Error (MAE): 0.062
Mean Squared Error (MSE): 0.01
Root Mean Squared Error (RMSE): 0.101
R2_score: 0.759787
Root Mean Squared Log Error (RMSLE): -2.288
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  0.759643
------------------------------------------------------------------------------------------------------------

C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

Model Name:  XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)
Mean Absolute Error (MAE): 0.06
Mean Squared Error (MSE): 0.009
Root Mean Squared Error (RMSE): 0.094
R2_score: 0.794772
Root Mean Squared Log Error (RMSLE): -2.367
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  0.794649
------------------------------------------------------------------------------------------------------------
Model Name:  Ridge()
Mean Absolute Error (MAE): 0.077
Mean Squared Error (MSE): 0.013
Root Mean Squared Error (RMSE): 0.116
R2_score: 0.686096
Root Mean Squared Log Error (RMSLE): -2.154
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  0.685908
------------------------------------------------------------------------------------------------------------
Model Name:  Lasso(alpha=0.1)
Mean Absolute Error (MAE): 0.158
Mean Squared Error (MSE): 0.043
Root Mean Squared Error (RMSE): 0.207
R2_score: -0.000129
Root Mean Squared Log Error (RMSLE): -1.575
Mean Absolute Percentage Error (MAPE): inf %
Adj R Square:  -0.000727
------------------------------------------------------------------------------------------------------------

C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
C:\Users\toant\AppData\Local\Temp\ipykernel_43744\3728460792.py:40: RuntimeWarning: divide by zero encountered in divide
  return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

In [69]:
models=['LinearRegression','DecisionTree','RandomForest', 'ExtraTrees', 'XGBoost' ,'RidgeRegression','LassoRegression']
result=pd.DataFrame({'Model_Name':models})
result['Adj_R_Square']=Results['Adj_R_Square']
result['Mean_Absolute_Error_MAE']=Results['Mean_Absolute_Error_MAE']
result['Root_Mean_Squared_Error_RMSE']=Results['Root_Mean_Squared_Error_RMSE']
result['Mean_Absolute_Percentage_Error_MAPE']=Results['Mean_Absolute_Percentage_Error_MAPE']
result['Mean_Squared_Error_MSE']=Results['Mean_Squared_Error_MSE']
result['Root_Mean_Squared_Log_Error_RMSLE']=Results['Root_Mean_Squared_Log_Error_RMSLE']
result['R2_score']=Results['R2_score']
result=result.sort_values(by='Adj_R_Square',ascending=False).reset_index(drop=True)
result

,Model_Name,Adj_R_Square,Mean_Absolute_Error_MAE,Root_Mean_Squared_Error_RMSE,Mean_Absolute_Percentage_Error_MAPE,Mean_Squared_Error_MSE,Root_Mean_Squared_Log_Error_RMSLE,R2_score
0,XGBoost,0.794649,0.059836,0.093771,inf,0.008793,-2.366902,0.794772
1,RandomForest,0.771184,0.060982,0.098984,inf,0.009798,-2.312802,0.771321
2,ExtraTrees,0.759643,0.061765,0.101449,inf,0.010292,-2.288198,0.759787
3,DecisionTree,0.757281,0.062062,0.101946,inf,0.010393,-2.283308,0.757426
4,LinearRegression,0.685914,0.077264,0.115970,inf,0.013449,-2.154428,0.686102
5,RidgeRegression,0.685908,0.077261,0.115971,inf,0.013449,-2.154418,0.686096
6,LassoRegression,-0.000727,0.158326,0.207003,inf,0.042850,-1.575020,-0.000129

In [70]:
res = result[['Model_Name','R2_score']]
res = res.reset_index(drop = True) 
res

         Model_Name  R2_score
0           XGBoost  0.794772
1      RandomForest  0.771321
2        ExtraTrees  0.759787
3      DecisionTree  0.757426
4  LinearRegression  0.686102
5   RidgeRegression  0.686096
6   LassoRegression -0.000129